### PR TITLE
Added Swap function

### PR DESCRIPTION
**Pull request by StrongDonald**

### CODE REVIEW

**Comment by Qsilver97** [comment]
uint8 Poolnum;
that seems to limit to a total of 255 pools, way too small
also all the calculations are 64bits which will clearly underflow and overflow, multiprecision math must be used.

happy to see the volunteer spirit!

**Comment by StrongDonald** [comment]
How much pool do we need?

**Comment by Qsilver97** [comment]
at least 65536 pools but it seems we can encode some extra info into a 32 bit field where 8 bits are for the type of pool (like how many user defined tokens, whether it has microTokens, maybe a few more useful info bits on the pool

with some tokens being able to have trillions of supply and you are just multiplying not sure what there is to discuss, we need to use multiprecision to stay far far away from any overflow or underflow and also to make sure we reach consensus on all nodes.

Seems all integers would be multiplied by a large enough number to get good resolution. 1T ?
Then use 256bit math

**Comment by StrongDonald** [comment]
"at least 65536 pools but it seems we can encode some extra info into a 32 bit field where 8 bits are for the type of pool (like how many user defined tokens, whether it has microTokens, maybe a few more useful info bits on the pool"

 - No problem.

"Seems all integers would be multiplied by a large enough number to get good resolution. 1T ?
Then use 256bit math"

-For this, we need to use the boost or GMP library. but core don't provide the boost and GMP library currently. Is it okay to add the libraries to core?

**Comment by Qsilver97** [comment]
you said that the multiprecision math was supported already...
you have to include ALL source code in the SC file and also make it compatible with QPI restrictions. It seems that making public entry points for the multiprecision would make sense so other SC can take advantage of such a large codebase

**Comment by StrongDonald** [comment]
"you said that the multiprecision math was supported already..."

- math_lib.h - At first I think this library supports much functions. but this library supports only +, -, / , * for unsigned long long.

"It seems that making public entry points for the multiprecision would make sense so other SC can take advantage of such a large codebase"

- I think we have to add this functions to math_lib.h.

**Comment by Qsilver97** [comment]
If adding to math_lib.h is possible then it is a good idea.

**Comment by StrongDonald** [comment]
If we use the boost library to develop the SC, it needs to add the boost library to math_lib.h. but this work is for core team. Naturally I can do this work. but I think currently my role is to develop the SC. so you can ask core team members to add the boost library for multiprecision work while I will complete the work for micro token.
what do you think about that? I will wait for your reply.

**Comment by Qsilver97** [comment]
I was told we have to put it in the SC file
they will not do the multiprecision in math_lib.h as that is not needed for network functioning only for SC
by having public entry points for the multiprecision calcs, we can even charge other SC small fee like 1QU each time

**Comment by StrongDonald** [comment]
I understand. so currently our goal is to implement the mutiprecision for SC. also is it okay to charge other SC 1QU fee? and 1QU fee would go to Qpool SC. okay?

**Comment by StrongDonald** [comment]
Okay, I will do that.

**Comment by StrongDonald** [comment]
but why can't send the message via discord?

**Comment by StrongDonald** [comment]
Should I work as volunteer continuously?

**Comment by StrongDonald** [comment]
Also spelunker have made the Lai workbench on Notion and invited me. but I don't know well how to use the my workbench.

**Comment by Qsilver97** [comment]
spelunker says this is the only way we can work together.

**Comment by StrongDonald** [comment]
I got it. so I will continue to work to implement the multipresicion.

**Comment by StrongDonald** [comment]
"This deliverable should also include a detailed table listing all identified unknowns and their estimated resolution times." - This was spelunker wants in last week for SOW. but I can't understand what he wants in detail. could you let me know about identified unknowns?

**Comment by Qsilver97** [comment]
do not worry about SoW, we are just working using github on volunteer basis.

**Comment by StrongDonald** [comment]
I can't the work as volunteer continuously.

**Comment by Qsilver97** [comment]
Upon completion and acceptance of the full version, there will be a bounty. The amount not determined yet.

**Comment by StrongDonald** [comment]
I got it. I will continue to work as volunteer until the amount is determined. but this chatting is very inconvenient. why can't we chatting via discord?

**Pull request merged**
