### PR TITLE
basic operation for multiprecision

### PR DESCRIPTION
**Pull request by StrongDonald**

### CODE REVIEW

**Comment by Qsilver97** [comment]
you seem to have structs with single byte entries first then the bigger ones with 8 or 16 bytes, this will create a gap in the structure for alignment.

again I ask that you put the largest structure elements first so any gaps in the structure will be in unused area. I hope you can see the advantage of not having any dead space in between structure elements and in some cases this will be a performance gain or even avoidance of memory alignment crashes

**Comment by StrongDonald** [comment]
I got it. I will clean all of the code.

**Comment by Qsilver97** [comment]
struct BIGNumberToString_output {
		uint8 len;
		uint8_128 result;
	};
	
	All these type of structs are backwards they should be: 
	
			uint8_128 result
				uint8 len;

Also is 128 bits enough? I thought 256 bits.

**Comment by Qsilver97** [comment]
For all the various fee multipliers please make a separate #define so we can easily understand the fee structure and also be able to tweak it

**Comment by Qsilver97** [comment]
BIGMultiple should be BIGMultiply

**Comment by StrongDonald** [comment]
> ```
> struct BIGNumberToString_output {
> 	uint8 len;
> 	uint8_128 result;
> };
> 
> All these type of structs are backwards they should be: 
> 
> 		uint8_128 result
> 			uint8 len;
> ```
> 
> Also is 128 bits enough? I thought 256 bits.

the length of 256bit string number is small than 128.

**Comment by Qsilver97** [comment]
For swaps I think we should be like QX and just charge the percentage of the swap amount. To do that I think you need to track the total fees from the BIG operations and then at the end subtract what is needed to add up to the exact swap fee amount. 
I do not see a swap fee #define

**Comment by StrongDonald** [comment]
> For all the various fee multipliers please make a separate #define so we can easily understand the fee structure and also be able to tweak it

sure, I will do that.

**Comment by StrongDonald** [comment]
> BIGMultiple should be BIGMultiply

will fix

**Comment by Qsilver97** [comment]
> > ```
> > struct BIGNumberToString_output {
> > 	uint8 len;
> > 	uint8_128 result;
> > };
> > 
> > All these type of structs are backwards they should be: 
> > 
> > 		uint8_128 result
> > 			uint8 len;
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Also is 128 bits enough? I thought 256 bits.
> 
> the length of 256bit string number is small than 128.

I see a bit confusing, how big is uint8_128 ?

**Comment by StrongDonald** [comment]
uint8_128 holds 128 uint8 elements.

**Comment by Qsilver97** [comment]
Please add back the original non-multiprecision code in comments so we can see the logic that is being implemented without having to reconstruct it from the BIG operations. This way we can look at what we are trying to calculate and also the actual BIG calculations to make sure they match

**Comment by StrongDonald** [comment]
https://github.com/Qsilver97/core/pull/10/files#diff-d7eca40616ae8905457a654576f4d08f5be9adc9b7769e45621ea5f9b8f48222R612-R616

**Comment by StrongDonald** [comment]
https://github.com/Qsilver97/core/pull/10/files#diff-d7eca40616ae8905457a654576f4d08f5be9adc9b7769e45621ea5f9b8f48222R766-R770

**Comment by StrongDonald** [comment]
I have already added the original non-multiprecision code.

**Pull request merged**
